[package]
name = "beetree"
version = "0.0.1"
repository = "https://github.com/Sladuca/beetree"
license = "MIT"
edition = "2018"
description = "A simple, generic, and serializable B+ Tree"
authors = [ "sladuca777@gmail.com" ]

[dependencies]
